name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "43 3 * * *"

permissions:
  contents: read

jobs:
  lint:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-cache-ubuntu-latest-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-ubuntu-latest-
      - name: Format check
        run: cargo fmt --verbose --check
      - name: Clippy
        run: cargo clippy --verbose

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-cache-ubuntu-latest-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-ubuntu-latest-
      - name: Build docs
        run: cargo doc --no-deps --document-private-items

  test:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    name: Build and Test
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-cache-${{ matrix.runner }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-${{ matrix.runner }}-
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  # Virtual job that can be configured as a required check before a PR can be merged.
  # As GitHub considers a check as successful if it is skipped, we need to check its status in
  # another workflow (check-required.yml) and create a check there.
  all-required-checks-done:
    name: All required checks done
    needs:
      - lint
      - docs
      - test
    runs-on: ubuntu-latest
    steps:
      - run: echo "All required checks done"
