name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "43 3 * * *"

permissions:
  contents: read

jobs:
  lint:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-cache-ubuntu-latest-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-ubuntu-latest-
      - name: Format check
        run: cargo fmt --verbose --check
      - name: Clippy
        run: cargo clippy --verbose

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-cache-ubuntu-latest-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-ubuntu-latest-
      - name: Build docs
        run: cargo doc --no-deps --document-private-items

  test:
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    name: Build and Test
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-cache-${{ matrix.runner }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: cargo-cache-${{ matrix.runner }}-
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  # A single job that succeeds if all jobs listed under 'needs' succeed.
  # This allows to configure a single job as a required check.
  # The 'needed' jobs then can be changed through pull-requests.
  all-jobs-succeeded:
    name: All jobs succeeded
    if: always()
    # the if clauses below have to reflect the number of jobs listed here
    needs:
      - lint
      - docs
      - test
    env:
      RESULTS: ${{ join(needs.*.result, ',') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Success"
        # we expect all required jobs to have success result
        if: env.RESULTS == 'success,success,success'
        run: true
        shell: bash
      - name: "Failure"
        # we expect all required jobs to have success result, fail otherwise
        if: env.RESULTS != 'success,success,success'
        run: false
        shell: bash
